name: harry_potter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: any
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4
  provider: ^6.1.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  package_rename: ^1.7.1
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  generate: true

package_rename_config:
  android:
    app_name: Hogwarts
    package_name: cat.cifovirtual.hogwarts
    override_old_package: com.example.harry_potter

  ios:
    app_name: Hogwarts
    bundle_name: cat.cifovirtual
    package_name: cat.cifovirtual.hogwarts